"""Shared schema and conservative field mappings for lead database imports."""

from __future__ import annotations

from dataclasses import dataclass


STANDARD_FIELDS: list[str] = [
    "lead_id",
    "company_id",
    "contact_id",
    "source_file",
    "source_sheet",
    "source_row",
    "source_database",
    "import_batch",
    "original_record_id",
    "company_name",
    "company_name_normalized",
    "legal_name",
    "tax_id",
    "company_registration_number",
    "company_type",
    "industry",
    "subindustry",
    "business_category",
    "company_size",
    "employee_count",
    "annual_revenue",
    "founding_year",
    "contact_name",
    "first_name",
    "last_name",
    "job_title",
    "department",
    "contact_role",
    "preferred_language",
    "email",
    "secondary_email",
    "phone",
    "mobile_phone",
    "secondary_phone",
    "website",
    "facebook_url",
    "instagram_url",
    "linkedin_url",
    "other_social_url",
    "address",
    "address_line_2",
    "postal_code",
    "city",
    "municipality",
    "district",
    "region",
    "country",
    "lead_status",
    "lead_type",
    "lead_priority",
    "lead_score",
    "estimated_potential",
    "products_of_interest",
    "likely_use_case",
    "current_supplier",
    "order_volume",
    "notes",
    "internal_notes",
    "tags",
    "email_status",
    "phone_status",
    "website_status",
    "validation_status",
    "duplicate_status",
    "enrichment_status",
    "review_required",
    "data_quality_score",
    "consent_status",
    "consent_source",
    "do_not_contact",
    "unsubscribe_status",
    "last_contacted_at",
    "next_contact_at",
    "campaign_status",
    "raw_company_name",
    "raw_contact_name",
    "raw_email",
    "raw_phone",
    "raw_address",
    "raw_notes",
    "raw_source_data",
    "created_at",
    "updated_at",
]


@dataclass(frozen=True)
class FieldDefinition:
    field_name: str
    description: str
    data_type: str
    required: bool
    example: str
    normalization_rule: str
    leadops_usage: str
    forgeos_notes: str


FIELD_DEFINITIONS: list[FieldDefinition] = [
    FieldDefinition(
        field,
        "Standard lead import field.",
        "text",
        field in {"lead_id", "source_file", "source_sheet", "source_row"},
        "",
        "Preserve raw values and normalize conservatively where applicable.",
        "LeadOps import and review.",
        "Tenant-scoped lead/customer onboarding data.",
    )
    for field in STANDARD_FIELDS
]


FIELD_ALIASES: dict[str, str] = {
    "empresa": "company_name",
    "nome empresa": "company_name",
    "nome da empresa": "company_name",
    "entidade": "company_name",
    "designacao": "company_name",
    "designação": "company_name",
    "nome": "company_name",
    "name": "company_name",
    "company": "company_name",
    "company name": "company_name",
    "organização": "company_name",
    "organizacao": "company_name",
    "organization": "company_name",
    "nif": "tax_id",
    "nipc": "tax_id",
    "tax id": "tax_id",
    "vat": "tax_id",
    "categoria": "business_category",
    "category": "business_category",
    "tipo": "lead_type",
    "setor": "industry",
    "sector": "industry",
    "industry": "industry",
    "atividade": "subindustry",
    "contacto": "contact_name",
    "contato": "contact_name",
    "contact": "contact_name",
    "pessoa contacto": "contact_name",
    "responsavel": "contact_name",
    "responsável": "contact_name",
    "cargo": "job_title",
    "funcao": "job_title",
    "função": "job_title",
    "email": "email",
    "e-mail": "email",
    "mail": "email",
    "correio eletrónico": "email",
    "correio electronico": "email",
    "telefone": "phone",
    "telemovel": "mobile_phone",
    "telemóvel": "mobile_phone",
    "mobile": "mobile_phone",
    "phone": "phone",
    "website": "website",
    "site": "website",
    "site web": "website",
    "url": "website",
    "facebook": "facebook_url",
    "instagram": "instagram_url",
    "linkedin": "linkedin_url",
    "morada": "address",
    "endereco": "address",
    "endereço": "address",
    "address": "address",
    "codigo postal": "postal_code",
    "código postal": "postal_code",
    "postal": "postal_code",
    "localidade": "city",
    "cidade": "city",
    "city": "city",
    "municipio": "municipality",
    "município": "municipality",
    "concelho": "municipality",
    "distrito": "district",
    "district": "district",
    "regiao": "region",
    "região": "region",
    "pais": "country",
    "país": "country",
    "country": "country",
    "observacoes": "notes",
    "observações": "notes",
    "notas": "notes",
    "notes": "notes",
}


LOOKUPS: dict[str, list[str]] = {
    "lead_status": ["new", "qualified", "review_required"],
    "lead_type": ["company", "association", "municipality", "education", "event", "unknown"],
    "lead_priority": ["low", "medium", "high"],
    "validation_status": ["valid", "partial", "invalid", "review_required"],
    "duplicate_status": ["unique", "exact_duplicate", "possible_duplicate"],
    "enrichment_status": ["not_started", "manual_review"],
    "campaign_status": ["not_started", "excluded", "ready_for_review"],
    "consent_status": ["unknown", "legitimate_interest_review_required", "do_not_contact"],
    "industries": [],
    "districts": [],
    "regions": [],
    "countries": ["Portugal"],
}


SOURCE_COLUMNS: list[str] = [
    "source_file",
    "source_sheet",
    "source_row",
    "source_database",
    "standardized_lead_id",
    "duplicate_group_id",
    "duplicate_status",
    "validation_status",
    "review_required",
    "raw_source_data",
]
