"""Canonical product import schema, field aliases, and source precedence."""

from __future__ import annotations

from dataclasses import dataclass

STANDARD_FIELDS: list[str] = [
    "product_id",
    "source_file",
    "source_sheet",
    "source_row",
    "source_database",
    "import_batch",
    "code",
    "designation",
    "short_name",
    "family",
    "article_type",
    "barcode",
    "attribute_mask_id",
    "tax_rate_label",
    "purchase_price_ex_vat",
    "purchase_price_inc_vat",
    "sale_price_ex_vat",
    "sale_price_inc_vat",
    "sales_unit",
    "capacity_unit",
    "extra_description",
    "packaging_quantity_hint",
    "supplier_reference",
    "customer_reference",
    "profit_tax_status",
    "validation_status",
    "duplicate_status",
    "review_required",
    "data_quality_score",
    "raw_source_data",
    "created_at",
    "updated_at",
]

EXCLUDED_SOURCE_FIELDS: frozenset[str] = frozenset(
    {
        "stock_atual",
        "stock_actual",
        "current_stock",
        "inventory_quantity",
        "quantity_on_hand",
        "controlo_remoto",
        "remote_control",
    }
)

SOURCE_PRECEDENCE: list[dict[str, str]] = [
    {
        "rank": "1",
        "source_kind": "standardized_workbook",
        "rule": "A generated Product_Database_Standardized.xlsx MASTER_PRODUCTS sheet wins over raw exports.",
    },
    {
        "rank": "2",
        "source_kind": "native_csv_export",
        "rule": "Semicolon CSV exports (e.g. artigos csv.csv) take precedence over HTML table exports.",
    },
    {
        "rank": "3",
        "source_kind": "xlsx_workbook",
        "rule": "Native .xlsx sheets are preferred over .xls when both exist for the same snapshot.",
    },
    {
        "rank": "4",
        "source_kind": "html_table_export",
        "rule": "HTML exports are fallback-only; truncated cells require review.",
    },
    {
        "rank": "5",
        "source_kind": "manual_field_mapping",
        "rule": "Explicit FIELD_MAPPING overrides beat automatic alias resolution.",
    },
    {
        "rank": "6",
        "source_kind": "barcode_resolution",
        "rule": "Dedicated barcode column wins; EAN-shaped product codes may be promoted only after confirmation.",
    },
    {
        "rank": "7",
        "source_kind": "price_resolution",
        "rule": "Ex-VAT (s/Imposto) prices are canonical; inc-VAT values are retained for audit only.",
    },
    {
        "rank": "8",
        "source_kind": "supplier_customer_refs",
        "rule": "Dedicated supplier/customer master files override inline product-row references when present.",
    },
]


@dataclass(frozen=True)
class FieldDefinition:
    field_name: str
    description: str
    data_type: str
    required: bool
    example: str
    normalization_rule: str
    forgeos_target: str


FIELD_DEFINITIONS: list[FieldDefinition] = [
    FieldDefinition(
        "code",
        "Tenant-unique product or article reference.",
        "text",
        True,
        "JHG-CUP-PP-330",
        "Trim whitespace; preserve alphanumeric prefixes.",
        "products.sku / products.product_code",
    ),
    FieldDefinition(
        "designation",
        "Full commercial description.",
        "text",
        True,
        "Personalized PP cup 330 ml",
        "Preserve original text; do not rewrite marketing copy.",
        "products.name / products.designation",
    ),
    FieldDefinition(
        "short_name",
        "ERP short label.",
        "text",
        False,
        "COPO PP 330",
        "Trim only.",
        "products.short_name (future)",
    ),
    FieldDefinition(
        "family",
        "Material or article family.",
        "text",
        False,
        "Plástico",
        "Map to controlled vocabulary after tenant confirmation.",
        "products.family",
    ),
    FieldDefinition(
        "article_type",
        "ERP article type such as Normal or shipping.",
        "text",
        False,
        "Normal",
        "Flag non-stock article types for review.",
        "products.lifecycle_status / process routing",
    ),
    FieldDefinition(
        "barcode",
        "EAN/GTIN barcode when present.",
        "text",
        False,
        "5601460006370",
        "Digits only; validate length 8/12/13/14.",
        "products.barcode",
    ),
    FieldDefinition(
        "purchase_price_ex_vat",
        "Purchase unit price excluding VAT.",
        "decimal",
        False,
        "12.3456",
        "Parse Portuguese decimal format; strip currency symbol.",
        "products.purchase_price",
    ),
    FieldDefinition(
        "sale_price_ex_vat",
        "Sale unit price excluding VAT.",
        "decimal",
        False,
        "15.0000",
        "Parse Portuguese decimal format; strip currency symbol.",
        "products.sale_price / products.base_price",
    ),
    FieldDefinition(
        "sales_unit",
        "Commercial sales unit of measure.",
        "text",
        False,
        "Unidade",
        "Normalize synonyms (Unidade, Milheiro, CX).",
        "products.sales_unit / products.purchase_unit",
    ),
    FieldDefinition(
        "capacity_unit",
        "Capacity or stocking unit.",
        "text",
        False,
        "Unidade",
        "Trim only.",
        "products.purchase_unit",
    ),
    FieldDefinition(
        "packaging_quantity_hint",
        "Pack size extracted from designation when explicit.",
        "integer",
        False,
        "2000",
        "Regex extract (N UN); never infer stock on hand.",
        "products.quantity_per_package",
    ),
    FieldDefinition(
        "supplier_reference",
        "Supplier code or name when supplied by source.",
        "text",
        False,
        "SUP-ACME-01",
        "Resolve against supplier master after confirmation.",
        "products.supplier_id",
    ),
    FieldDefinition(
        "customer_reference",
        "Customer-specific article reference when supplied.",
        "text",
        False,
        "CUST-REF-001",
        "Customer-specific mapping only; not in current JH export.",
        "customer_product_refs (future)",
    ),
]

FIELD_ALIASES: dict[str, str] = {
    "referencia": "code",
    "referência": "code",
    "ref": "code",
    "codigo": "code",
    "código": "code",
    "cod.": "code",
    "sku": "code",
    "descricao": "designation",
    "descrição": "designation",
    "description": "designation",
    "nome curto 1": "short_name",
    "nome curto": "short_name",
    "familia": "family",
    "família": "family",
    "family": "family",
    "tipo de artigo": "article_type",
    "tipo artigo": "article_type",
    "article type": "article_type",
    "cod. barras": "barcode",
    "cód. barras": "barcode",
    "codigo barras": "barcode",
    "código barras": "barcode",
    "barcode": "barcode",
    "ean": "barcode",
    "gtin": "barcode",
    "id mascara atributo": "attribute_mask_id",
    "id máscara atributo": "attribute_mask_id",
    "taxa": "tax_rate_label",
    "preco de compra s/imposto": "purchase_price_ex_vat",
    "preço de compra s/imposto": "purchase_price_ex_vat",
    "preco compra s/iva": "purchase_price_ex_vat",
    "preço compra s/iva": "purchase_price_ex_vat",
    "preco de compra c/imposto": "purchase_price_inc_vat",
    "preço de compra c/imposto": "purchase_price_inc_vat",
    "preco s/imposto": "sale_price_ex_vat",
    "preço s/imposto": "sale_price_ex_vat",
    "preco venda s/iva": "sale_price_ex_vat",
    "preço venda s/iva": "sale_price_ex_vat",
    "preco c/imposto": "sale_price_inc_vat",
    "preço c/imposto": "sale_price_inc_vat",
    "preco venda c/iva": "sale_price_inc_vat",
    "preço venda c/iva": "sale_price_inc_vat",
    "unidade de venda": "sales_unit",
    "unidade venda": "sales_unit",
    "unidade de capacidade": "capacity_unit",
    "unidade capacidade": "capacity_unit",
    "descricao extra": "extra_description",
    "descrição extra": "extra_description",
    "fornecedor": "supplier_reference",
    "supplier": "supplier_reference",
    "supplier code": "supplier_reference",
    "cliente": "customer_reference",
    "customer": "customer_reference",
    "customer reference": "customer_reference",
    "imposto sobre o lucro": "profit_tax_status",
    "stock atual": "stock_atual",
    "controlo remoto 5": "controlo_remoto",
    "controlo remoto": "controlo_remoto",
}

SOURCE_COLUMNS: list[str] = [
    "source_file",
    "source_sheet",
    "source_row",
    "source_database",
    "import_batch",
    "standardized_product_id",
    "duplicate_group_id",
    "duplicate_status",
    "validation_status",
    "review_required",
    "raw_source_data",
]
